name: Sync And Deploy to Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: ${{ steps.get-url.outputs.url }}

    steps:
    - name: Set Environment URL
      id: get-url
      run: echo "url=${{ secrets.PRODUCTION_URL }}" >> $GITHUB_OUTPUT

    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Run Remote Deployment Script
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          /bin/bash /scripts/pela/deploy.sh
